### ISSUE TITLE
KICAD TO DO

### ISSUE THREAD

**Issue by idelcampo45** [MOSH-Insa-Toulouse/2023-2024_4GP_DELCAMPO_VALENCIA#5]
### KICAD à faire:

- [x] footprint pour modules ( flex, encod)
- [x] Mesurer espacement pour flexsensor
- [x] Routage PCB
- [x] Label imput?
- [x] D10,11,12?

**Comment by izanvr** [comment]
Espacement pour flexsensor de 2mm entre pates, mais pour suivre consignes j'ai mis 2,5mm
